"""empty message

Revision ID: 8bb8916b03e4
Revises: 
Create Date: 2020-09-10 11:40:59.747738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb8916b03e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_badges_expire_time'), 'badges', ['expire_time'], unique=False)
    op.create_table('building',
    sa.Column('id_corso', sa.Integer(), nullable=False),
    sa.Column('struttura_des', sa.String(length=120), nullable=True),
    sa.Column('struttura_id', sa.String(length=10), nullable=True),
    sa.Column('struttura_ga_id', sa.Integer(), nullable=True),
    sa.Column('corso_ga_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_corso')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('userAccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('classroom', sa.String(length=16), nullable=True),
    sa.Column('autocertification', sa.Boolean(), nullable=True),
    sa.Column('grpId', sa.Integer(), nullable=True),
    sa.Column('persId', sa.Integer(), nullable=True),
    sa.Column('stuId', sa.Integer(), nullable=True),
    sa.Column('matId', sa.Integer(), nullable=True),
    sa.Column('matricola', sa.String(length=16), nullable=True),
    sa.Column('cdsId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userAccess_username'), 'userAccess', ['username'], unique=True)
    op.create_table('userAccessFull',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('classroom', sa.String(length=16), nullable=True),
    sa.Column('autocertification', sa.Boolean(), nullable=True),
    sa.Column('grpId', sa.Integer(), nullable=True),
    sa.Column('persId', sa.Integer(), nullable=True),
    sa.Column('stuId', sa.Integer(), nullable=True),
    sa.Column('matId', sa.Integer(), nullable=True),
    sa.Column('matricola', sa.String(length=16), nullable=True),
    sa.Column('cdsId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userAccessFull_username'), 'userAccessFull', ['username'], unique=True)
    op.create_table('userFood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nome_bar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userFood_email'), 'userFood', ['email'], unique=True)
    op.create_index(op.f('ix_userFood_nome_bar'), 'userFood', ['nome_bar'], unique=True)
    op.create_index(op.f('ix_userFood_username'), 'userFood', ['username'], unique=True)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('tipologia', sa.String(length=120), nullable=True),
    sa.Column('descrizione', sa.String(length=120), nullable=True),
    sa.Column('prezzo', sa.Integer(), nullable=True),
    sa.Column('sempre_attivo', sa.Boolean(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('user_username', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['userFood.nome_bar'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_data'), 'food', ['data'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_index(op.f('ix_food_data'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_userFood_username'), table_name='userFood')
    op.drop_index(op.f('ix_userFood_nome_bar'), table_name='userFood')
    op.drop_index(op.f('ix_userFood_email'), table_name='userFood')
    op.drop_table('userFood')
    op.drop_index(op.f('ix_userAccessFull_username'), table_name='userAccessFull')
    op.drop_table('userAccessFull')
    op.drop_index(op.f('ix_userAccess_username'), table_name='userAccess')
    op.drop_table('userAccess')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('building')
    op.drop_index(op.f('ix_badges_expire_time'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
