"""empty message

Revision ID: df38346be9d5
Revises: 8bb8916b03e4
Create Date: 2020-09-10 12:19:52.859252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df38346be9d5'
down_revision = '8bb8916b03e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userAccessFull_username', table_name='userAccessFull')
    op.drop_table('userAccessFull')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userAccessFull',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('classroom', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('autocertification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('grpId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('persId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stuId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('matId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('matricola', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('cdsId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.CheckConstraint('`autocertification` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_userAccessFull_username', 'userAccessFull', ['username'], unique=True)
    # ### end Alembic commands ###
